# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AskagramMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AskagramMobile
  pod 'RNMobileCenter', '~> 0.1.0'
  pod 'MobileCenter', '~> 0.3.0'

  target 'AskagramMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
